#!/usr/bin/env node
/*
 * rebrand — apply a Brand Manifest to the scaffold.
 *
 * Reads `brand/<active>/manifest.json` and regenerates the brand-injectable
 * regions of styles/{settings,primitives,fonts}.css. Semantic.css is never
 * touched (role contract is brand-invariant).
 *
 * Usage:
 *   node scripts/rebrand.mjs                       # uses brand/active or first brand/ folder
 *   node scripts/rebrand.mjs --brand=sabic         # uses brand/sabic/manifest.json
 *   node scripts/rebrand.mjs --primary=#FF6600 \   # manual ad-hoc override (skips manifest)
 *     --display=Inter --body=system-ui --controls=rounded
 *
 * Markers in CSS files:
 *   /* @brand:colors *\/ ... /* @brand:end *\/
 *   /* @brand:typography *\/ ... /* @brand:end *\/
 *   /* @brand:control-radius *\/ ... /* @brand:end *\/
 */

import { readFile, writeFile, readdir } from 'node:fs/promises'
import { existsSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const root = dirname(dirname(fileURLToPath(import.meta.url)))

// ── argv parsing ────────────────────────────────────────────────────
const args = Object.fromEntries(
  process.argv.slice(2)
    .filter((a) => a.startsWith('--'))
    .map((a) => {
      const [k, ...rest] = a.slice(2).split('=')
      return [k, rest.join('=') || true]
    }),
)

// ── load manifest (or build one from --primary/--display/...) ───────
async function pickManifest() {
  if (args.primary || args.display || args.body || args.controls) {
    return buildAdHocManifest(args)
  }
  const brandName = args.brand || (await firstBrandFolder())
  if (!brandName) throw new Error('No brand/ folder found and no --primary flag given.')
  const path = join(root, 'brand', brandName, 'manifest.json')
  if (!existsSync(path)) throw new Error(`brand/${brandName}/manifest.json not found`)
  return JSON.parse(await readFile(path, 'utf8'))
}

async function firstBrandFolder() {
  const dir = join(root, 'brand')
  if (!existsSync(dir)) return null
  const entries = await readdir(dir, { withFileTypes: true })
  const folders = entries.filter((e) => e.isDirectory()).map((e) => e.name)
  if (folders.includes('active')) return 'active'
  return folders[0] || null
}

function buildAdHocManifest({ primary, display, body, controls }) {
  if (!primary) throw new Error('--primary=#HEX required when not using a brand folder')
  return {
    schemaVersion: 1,
    brand: {
      name: 'ad-hoc',
      colors: { primary: { primary, scale: generateScaleFromPrimary(primary) } },
      typography: {
        display: { family: display || 'system-ui', fallbacks: ['ui-sans-serif', 'sans-serif'], weights: [400, 600], source: { kind: 'system' } },
        body:    { family: body    || 'system-ui', fallbacks: ['ui-sans-serif', 'sans-serif'], weights: [400, 600], source: { kind: 'system' } },
        mono:    { family: 'ui-monospace', fallbacks: ['Menlo', 'monospace'], weights: [400], source: { kind: 'system' } },
      },
      radius: { controls: controls || 'pill' },
    },
  }
}

// ── color scale generator (when manifest gives only primary) ────────
// Simple lightness ladder around the primary; not OKLCH-perfect but good
// enough as a fallback so devs aren't blocked.
function generateScaleFromPrimary(hex) {
  const [r, g, b] = hexToRgb(hex)
  const stops = ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900']
  const lightnessOffsets = [0.92, 0.78, 0.62, 0.42, 0.2, 0, -0.1, -0.22, -0.35, -0.5]
  const out = {}
  for (let i = 0; i < stops.length; i++) {
    const t = lightnessOffsets[i]
    const lighten = (v) => Math.round(t >= 0 ? v + (255 - v) * t : v * (1 + t))
    out[stops[i]] = rgbToHex(lighten(r), lighten(g), lighten(b))
  }
  return out
}

function hexToRgb(hex) {
  const m = hex.replace('#', '')
  const v = m.length === 3 ? m.split('').map((c) => c + c).join('') : m
  return [parseInt(v.slice(0, 2), 16), parseInt(v.slice(2, 4), 16), parseInt(v.slice(4, 6), 16)]
}

function rgbToHex(r, g, b) {
  return '#' + [r, g, b].map((v) => Math.max(0, Math.min(255, v)).toString(16).padStart(2, '0')).join('')
}

// ── block generators ────────────────────────────────────────────────
function genColorsBlock(manifest) {
  const scale = manifest.brand.colors.primary.scale
  const lines = ['  /* @brand:colors — regenerated by `npm run rebrand` from brand/<active>/manifest.json */']
  for (const stop of ['50', '100', '200', '300', '400', '500', '600', '700', '800', '900']) {
    // base is one space after colon; 2-char stops need one extra space to align hex
    const pad = stop.length === 2 ? ' ' : ''
    const note = stop === '400' ? '   /* Primary */' : ''
    lines.push(`  --brand-${stop}: ${pad}${scale[stop]};${note}`)
  }
  lines.push('  /* @brand:end */')
  return lines.join('\n')
}

// CSS generic font keywords that must NOT be quoted (per CSS spec — quoting
// them turns them into a regular custom family name, defeating the fallback).
const GENERIC_FAMILIES = new Set([
  'serif', 'sans-serif', 'monospace', 'cursive', 'fantasy',
  'system-ui', 'ui-sans-serif', 'ui-serif', 'ui-monospace', 'ui-rounded',
  'math', 'emoji', 'fangsong',
])

function quoteFamily(name) {
  return GENERIC_FAMILIES.has(name) ? name : `'${name}'`
}

function genTypographyBlock(manifest) {
  const t = manifest.brand.typography
  const fmt = (f) => [f.family, ...f.fallbacks].map(quoteFamily).join(', ')
  const lines = [
    '  /* @brand:typography — regenerated by `npm run rebrand` */',
    `  --font-family:         ${fmt(t.body)};`,
    `  --font-family-display: ${fmt(t.display)};`,
    `  --font-family-mono:    ${fmt(t.mono)};`,
    '  /* @brand:end */',
  ]
  return lines.join('\n')
}

function genControlRadiusBlock(manifest) {
  const map = {
    pill:    'var(--radius-full)',
    rounded: 'var(--radius)',
    sharp:   '0',
  }
  const value = map[manifest.brand.radius?.controls || 'rounded']
  return [
    '  /* @brand:control-radius — regenerated by `npm run rebrand` */',
    `  --control-radius:       ${value};`,
    '  /* @brand:end */',
  ].join('\n')
}

function genFontsCss(manifest) {
  const out = [`/* FONTS — regenerated by \`npm run rebrand\` from brand/<active>/manifest.json. */`, '']
  for (const role of ['display', 'body', 'mono']) {
    const f = manifest.brand.typography[role]
    if (!f || f.source.kind === 'system') continue
    if (f.source.kind === 'google') {
      out.push(`@import url('${f.source.url}');`, '')
      continue
    }
    if (f.source.kind === 'self-hosted') {
      for (const file of f.source.files) {
        out.push(
          '@font-face {',
          `  font-family: '${f.family}';`,
          `  src: url('${file.path}') format('woff2');`,
          /* A range, not a number, when the file is a VARIABLE font: one file
           * then covers every weight the system declares, which is why there is
           * one file per subset here rather than one per weight. */
          `  font-weight: ${file.weight};`,
          `  font-style: normal;`,
          `  font-display: swap;`,
          /* Present when the family is split by script: the browser downloads a
           * subset only if the page actually uses a character from it. */
          ...(file.unicodeRange ? [`  unicode-range: ${file.unicodeRange};`] : []),
          '}',
          '',
        )
      }
    }
  }
  return out.join('\n').trimEnd() + '\n'
}

// ── block replacer ──────────────────────────────────────────────────
function replaceBlock(source, marker, replacement) {
  const start = `/* @brand:${marker}`
  const end = '/* @brand:end */'
  const startIdx = source.indexOf(start)
  if (startIdx === -1) {
    console.warn(`! marker @brand:${marker} not found, skipping`)
    return source
  }
  const lineStart = source.lastIndexOf('\n', startIdx) + 1
  const endIdx = source.indexOf(end, startIdx)
  if (endIdx === -1) throw new Error(`marker @brand:${marker} has no matching @brand:end`)
  const lineEnd = source.indexOf('\n', endIdx)
  return source.slice(0, lineStart) + replacement + source.slice(lineEnd === -1 ? source.length : lineEnd)
}

// ── main ────────────────────────────────────────────────────────────
async function main() {
  const manifest = await pickManifest()
  const brandName = manifest.brand.name
  console.log(`→ applying brand: ${brandName}`)

  // settings.css: typography + control-radius blocks
  const settingsPath = join(root, 'styles', 'settings.css')
  let settings = await readFile(settingsPath, 'utf8')
  settings = replaceBlock(settings, 'typography', genTypographyBlock(manifest))
  settings = replaceBlock(settings, 'control-radius', genControlRadiusBlock(manifest))
  await writeFile(settingsPath, settings)
  console.log('  styles/settings.css updated (typography, control-radius)')

  // primitives.css: brand colors block
  const primitivesPath = join(root, 'styles', 'primitives.css')
  let primitives = await readFile(primitivesPath, 'utf8')
  primitives = replaceBlock(primitives, 'colors', genColorsBlock(manifest))
  await writeFile(primitivesPath, primitives)
  console.log('  styles/primitives.css updated (brand colors)')

  // fonts.css: full regen
  const fontsPath = join(root, 'styles', 'fonts.css')
  await writeFile(fontsPath, genFontsCss(manifest))
  console.log('  styles/fonts.css regenerated')

  console.log(`✓ brand '${brandName}' applied. dev server will HMR.`)
}

main().catch((err) => { console.error(err); process.exit(1) })
